apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-books
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hko/data
