apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/tensorflow-notebook
        ports:
        - containerPort: 8888
        volumeMounts:
        - mountPath: “/books”
          name: j-books
      volumes:
      - name: j-books
        persistentVolumeClaim:
          claimName: jupyter-books
